# Generated by Django 3.2.9 on 2022-03-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='departement',
        ),
    ]
