# Generated by Django 3.2.9 on 2022-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ICT', 'ICT'), ('TE', 'TE'), ('ME', 'ME'), ('ECO', 'ECO'), ('ENG', 'ENG'), ('BBA', 'BBA'), ('PHA', 'PHA'), ('BGE', 'BGE'), ('BMB', 'BMB'), ('CPS', 'CPS'), ('ESRM', 'ESRM'), ('CHEM', 'CHEM'), ('PHY', 'PHY'), ('MATH', 'MATH'), ('STAT', 'STAT')], default='CSE', max_length=120),
        ),
    ]
