# Generated by Django 4.1.6 on 2023-02-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_examcommitte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.CharField(
                        choices=[
                            ("authentication", "authentication"),
                            ("student", "student"),
                            ("faculty", "faculty"),
                            ("stuff", "stuff"),
                            ("chairman", "chairman"),
                            ("examcontroller", "examcontroller"),
                            ("examcommite", "examcommite"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
